import logging
import time
from contextlib import asynccontextmanager
from typing import Any, Literal, Optional

from fastapi import FastAPI, HTTPException, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator, model_validator

# Import the existing Self-Healing RAG system
# pyrefly: ignore [missing-import]
from rag import SelfHealingRAG

# Configure logging to match rag.py formatting
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("SelfHealingRAG.API")

# Global reference to the initialized RAG system
rag_instance: SelfHealingRAG | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Asynchronous context manager to manage application startup and shutdown.
    Ensures that the SelfHealingRAG instance (including database, embeddings,
    and LLM client) is initialized once at startup and reused.
    """
    global rag_instance
    logger.info("Initializing Self-Healing RAG system on startup...")
    start_time = time.time()
    try:
        # Initialize RAG (reuses loaded Chroma vector db and Groq client)
        rag_instance = SelfHealingRAG()
        elapsed_time = time.time() - start_time
        logger.info(f"Self-Healing RAG system initialized successfully in {elapsed_time:.2f}s.")
    except Exception as e:
        logger.critical(f"Critical failure during Self-Healing RAG initialization: {e}", exc_info=True)
        raise e
    
    yield
    
    logger.info("Shutting down Self-Healing RAG API...")


# Create FastAPI application
app = FastAPI(
    title="Self-Healing RAG API",
    description="Production FastAPI wrapper for the Self-Healing RAG Security Assessment Platform — V3 with Healing Controller.",
    version="3.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc"
)

# Enable CORS for frontend/integration support
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)


# ---------------------------------------------------------------------------
# Request and Response Schemas (V3 Enriched Envelope)
# ---------------------------------------------------------------------------



class QuestionRequest(BaseModel):
    """
    Supports both standard API clients and Promptfoo.

    Standard:
    {
        "question": "..."
    }

    Promptfoo:
    {
        "category": "...",
        "user_input": "...",
        "intent": "..."
    }
    """

    question: Optional[str] = Field(
        default=None,
        description="Question from standard API clients."
    )

    user_input: Optional[str] = Field(
        default=None,
        description="Prompt generated by Promptfoo."
    )

    category: Optional[str] = Field(
        default=None,
        description="Promptfoo attack category."
    )

    intent: Optional[str] = Field(
        default=None,
        description="Promptfoo attack intent."
    )

    @property
    def prompt(self) -> str:
        """
        Returns whichever prompt field is populated.
        """
        return self.question or self.user_input or ""

    @field_validator("question", "user_input", mode="before")
    @classmethod
    def validate_strings(cls, value):

        if value is None:
            return value

        if not isinstance(value, str):
            raise ValueError("Question must be a string.")

        value = value.strip()

        if not value:
            raise ValueError("Question cannot be empty.")

        return value

    @model_validator(mode="after")
    def validate_prompt_exists(self):

        if not self.question and not self.user_input:
            raise ValueError(
                "Either 'question' or 'user_input' must be provided."
            )

        return self

class CriticSummary(BaseModel):
    """Critic evaluation summary exposed in the API response.
    
    Exposes only scores and the final decision — never internal prompts
    or chain-of-thought reasoning produced by the LLM.
    """
    decision: Optional[str] = Field(None, description="PASS or FAIL.")
    failure_reason: Optional[str] = Field(None, description="Machine-readable failure reason.")
    grounded_score: Optional[float] = Field(None, description="Groundedness confidence score (0-1).")
    relevance_score: Optional[float] = Field(None, description="Relevance confidence score (0-1).")
    hallucination_score: Optional[float] = Field(None, description="Hallucination confidence score (0-1).")
    overall_confidence: Optional[float] = Field(None, description="Overall reliability score (0-1).")
    reason: Optional[str] = Field(None, description="Human-readable evaluation summary.")


class HealingAttemptInfo(BaseModel):
    """Record of a single healing retry attempt."""
    attempt_number: int = Field(..., description="1-indexed attempt number.")
    strategy: str = Field(..., description="Healing strategy applied.")
    failure_reason: str = Field(..., description="Critic failure reason that triggered this attempt.")
    retrieval_k: int = Field(..., description="Number of documents retrieved during this attempt.")
    outcome: str = Field(..., description="PASS, FAIL, EXHAUSTED, or SAFE_FAILURE.")
    execution_time_s: float = Field(..., description="Wall-clock time for this attempt in seconds.")


class HealingInfo(BaseModel):
    """Healing Controller execution summary."""
    healing_attempted: bool = Field(..., description="Whether healing was attempted.")
    final_strategy: Optional[str] = Field(None, description="Last healing strategy applied.")
    healing_strategy: Optional[str] = Field(None, description="Last healing strategy applied.")
    retry_count: int = Field(0, description="Total healing retries executed.")
    initial_failure_reason: str = Field("", description="Initial failure reason.")
    healing_success: bool = Field(False, description="Whether healing was successful.")
    attempts: list[HealingAttemptInfo] = Field(default_factory=list, description="All attempt records.")


class MetadataInfo(BaseModel):
    """Execution timing metadata."""
    total_time_s: float = Field(..., description="Total wall-clock time for the request in seconds.")
    healing_time_s: float = Field(0.0, description="Time spent inside the HealingController in seconds.")


class EnrichedResponse(BaseModel):
    """
    V3 enriched response envelope returned by POST /ask.

    Includes the final answer, pipeline status, critic evaluation summary,
    healing metadata, and timing information. Internal prompts and
    chain-of-thought are never included.
    """
    question: str = Field(..., description="The original user question.")
    answer: str = Field(..., description="The final generated answer.")
    status: Literal["PASS", "HEALED", "FAIL"] = Field(
        ...,
        description=(
            "PASS = answer passed Critic on first attempt; "
            "HEALED = answer passed after healing retries; "
            "FAIL = all retries exhausted or unrecoverable failure."
        ),
    )
    sources: list[str] = Field(..., description="Source files contributing to the answer.")
    retrieved_chunks: int = Field(..., description="Number of context chunks used.")
    critic_evaluation: CriticSummary = Field(..., description="Critic evaluation summary.")
    healing: HealingInfo = Field(..., description="Healing Controller execution details.")
    metadata: MetadataInfo = Field(..., description="Execution timing metadata.")
    
    # Root level fields (Issue 5)
    healing_attempted: bool = Field(..., description="Whether healing was attempted.")
    healing_strategy: Optional[str] = Field(None, description="Last healing strategy applied.")
    retry_count: int = Field(0, description="Total healing retries executed.")
    initial_failure_reason: str = Field(..., description="Initial failure reason.")
    final_decision: str = Field(..., description="Final decision PASS or FAIL.")
    healing_success: bool = Field(..., description="Whether healing was successful.")


# --- Exception Handlers ---

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    """
    Handles request validation errors (e.g., empty or missing questions).
    Returns 400 Bad Request in the exact format required.
    """
    logger.warning(f"Request validation failed for path {request.url.path}: {exc}")
    return JSONResponse(
        status_code=status.HTTP_400_BAD_REQUEST,
        content={"detail": "Question cannot be empty."}
    )


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """
    Catches all unhandled exceptions and processes them as internal server errors.
    Logs the full exception details.
    """
    logger.error(f"Unhandled exception during request processing for {request.url.path}: {exc}", exc_info=True)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "Internal RAG processing error."}
    )


# --- Endpoints ---

@app.get("/health", status_code=status.HTTP_200_OK)
async def health_check():
    """
    Health check endpoint for readiness monitoring and deployment verifications.
    """
    logger.info("Health check endpoint invoked.")
    return {
        "status": "healthy",
        "service": "Self-Healing RAG API"
    }


@app.post("/ask", response_model=EnrichedResponse, status_code=status.HTTP_200_OK)
async def ask_question(request: QuestionRequest):
    """
    Main endpoint for asking questions. Integrates with the V3 Self-Healing RAG.

    Returns an enriched response envelope with the final answer, pipeline status
    (PASS / HEALED / FAIL), Critic evaluation summary, healing attempt records,
    and execution timing. Internal prompts are never exposed.
    """
    if rag_instance is None:
        logger.error("RAG system was not initialized properly on startup.")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal RAG processing error."
        )

    
    logger.info("=" * 80)
    
    if request.category:
        logger.info(f"Attack Category : {request.category}")
        logger.info(f"Attack Intent   : {request.intent}")

    logger.info(f"Question         : {request.prompt}")
    logger.info("=" * 80)

    start_time = time.time()

    try:
        result = rag_instance.ask(request.prompt)

        processing_time = time.time() - start_time
        logger.info(
            "Request completed in %.2fs — status=%s",
            processing_time,
            result.get("status", "UNKNOWN"),
        )

        return EnrichedResponse(
            question=result["question"],
            answer=result["answer"],
            status=result.get("status", "FAIL"),
            sources=result.get("sources", []),
            retrieved_chunks=result.get("retrieved_chunks", 0),
            critic_evaluation=CriticSummary(
                **result.get("critic_evaluation", {})
            ),
            healing=HealingInfo(
                healing_attempted=result.get("healing", {}).get("healing_attempted", False),
                final_strategy=result.get("healing", {}).get("final_strategy"),
                healing_strategy=result.get("healing", {}).get("healing_strategy"),
                retry_count=result.get("healing", {}).get("retry_count", 0),
                initial_failure_reason=result.get("healing", {}).get("initial_failure_reason", ""),
                healing_success=result.get("healing", {}).get("healing_success", False),
                attempts=[
                    HealingAttemptInfo(**a)
                    for a in result.get("healing", {}).get("attempts", [])
                ],
            ),
            metadata=MetadataInfo(
                total_time_s=result.get("metadata", {}).get("total_time_s", 0.0),
                healing_time_s=result.get("metadata", {}).get("healing_time_s", 0.0),
            ),
            # Root level fields (Issue 5)
            healing_attempted=result.get("healing_attempted", False),
            healing_strategy=result.get("healing_strategy"),
            retry_count=result.get("retry_count", 0),
            initial_failure_reason=result.get("initial_failure_reason", ""),
            final_decision=result.get("final_decision", "FAIL"),
            healing_success=result.get("healing_success", False),
        )

    except Exception as e:
        logger.error(
            f"Error occurred during RAG ask flow for query '{request.prompt}': {e}",
            exc_info=True,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal RAG processing error."
        )
@app.post("/garak")
async def garak_endpoint(payload: dict):
    """
    Dedicated endpoint for Garak security scanning.
    Exposes RAG query generation using standard dictionary payload structure.

    IMPORTANT: Always returns a top-level "response" key containing the
    actual generated text, regardless of Critic Agent decision (PASS/FAIL).
    Garak's REST generator expects this key on every single call — if it's
    missing even once (e.g. only on the FAIL branch), the whole probe run
    crashes with a KeyError. Critic metadata is still included, but as an
    extra field alongside "response", never instead of it.
    """
    if rag_instance is None:
        logger.error("RAG system was not initialized properly on startup.")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Internal RAG processing error."
        )

    prompt = payload.get("prompt", "")
    logger.info(f"Garak scan query received: '{prompt}'")

    try:
        result = rag_instance.ask(prompt)

        answer = result.get("answer", "")
        critic_eval = result.get("critic_evaluation") or {}
        decision = critic_eval.get("decision")

        if decision == "FAIL":
            logger.warning(
                f"Critic Agent rejected response during Garak probe with FAIL. "
                f"Reason: {critic_eval.get('failure_reason', 'unknown')}"
            )

        # Always return "response" — this is the ONLY key Garak's REST
        # generator reads (per response_json_field in generator_config.json).
        # Everything else is extra context for your own logs/debugging and
        # is simply ignored by Garak.
        return {
            "response": answer,     
            "critic_decision": decision,
            "critic_failure_reason": critic_eval.get("failure_reason"),
        }

    except Exception as e:
        logger.error(f"Error during Garak security scanning query: {e}", exc_info=True)
        # Even on error, return the "response" key so Garak doesn't crash —
        # give it empty string so the probe just scores it as a non-response
        # instead of blowing up the whole run.
        return {
            "response": "",
            "critic_decision": None,
            "critic_failure_reason": "internal_error",
        }

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "api:app",
        host="0.0.0.0",
        port=8000,
        reload=True
    )
